### ISSUE TITLE
Proposal to change output destination

### ISSUE THREAD

**Issue by t13801206** [jsakamoto/PublishSPAforGitHubPages.Build#1]
Thanks for the great library.

It is true that the output destination of "peaceiris/actions-gh-pages" is the `public` folder.
On the other hand, as you wrote "These steps are applied to the wwwroot folder under the **publish** folder.", the output destination is the `publish` folder by .NET convention.

So I think we should use `dotnet publish {YourSolution}.sln -c:Release -o:publish` would be better.

**Comment by jsakamoto** [comment]
@t13801206 Thank you for your proposal! 👍

Hum... "the publish folder" doesn't mean the `./publish` path absolutely.
"the publish folder" just means "one of the configuration values you specified when you build".
"the publish folder" can be any folder such as `./foo`, `../fizz/buzz`, etc. 
And this package will track "the public folder" that you specified.

And on the .NET convention, publish folder is `./bin/$(Configuration)/$(TargetFramework)/publish`, is not `./publish`, isn't it?

So your comment has made me a bit confusing.

But anyway, I don't mind if the publish folder is anywhere actually, so I'll accept your proposal and your pull request if you feel the `./publish` folder is more appropriate than the `./public` folder.

Again, thank you for your contribution!
